name: my-workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: make build

      - name: Execute Gradle test
        run: make test

      - name: Execute Gradle checkstyleMain & checkstyleTest
        run: make lint